FROM python:3.10

WORKDIR /opt

COPY ./requirements.txt /opt/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /opt/requirements.txt

COPY ./app /opt/api

ENV MILVUS_INSTANCE_NAME=default
ENV MILVUS_HOST=localhost
ENV MILVUS_PORT=19530

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "80"]
