name: Checks
on: [pull_request]

jobs:

  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install "black<23"
    - run: black --diff --check $(git ls-files '*.py')

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install pylint==v3.0.0a3 
    - run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')

  type-check:
    runs-on: ubuntu-latest
    name: Type Check
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install mypy==v0.902
    - run: mypy --strict $(git ls-files '*.py')